# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.systemd.enable = true; # added this from a forum post but might need to delete
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  #fileSystems."/" =
  #  { device = "/dev/disk/by-uuid/475e6d01-b8a2-465f-8075-e55a697fcbdf";
  #    fsType = "ext4";
  #  };
  
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/475e6d01-b8a2-465f-8075-e55a697fcbdf";
      fsType = "ext4";
    };
    #"/data" = {
    #  device = "/dev/disk/by-uuid/57795a11-fade-4a77-9593-31ff05ec5d87";
    #  fsType = "ext4";
    #};
  };

  boot.initrd.luks.devices."luks-c2464cd0-14e0-4361-91f6-3f88b08a188c".device = "/dev/disk/by-uuid/c2464cd0-14e0-4361-91f6-3f88b08a188c";
  #boot.initrd.luks.devices."


  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E5A1-0F28";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  #services.mdadm = {
  #  enable = true;
  #  devices = ["/dev/md0"];
  #};


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
